# If not running interactively, don't do anything
[[ $- != *i* ]] && return

. $HOME/.bashrc_pc_specific

HISTSIZE=15000
HISTFILESIZE=20000

alias ls="ls --color"

# Have the prompt default to be the pwd
export PS1="\w$ "

#Case insenstive completion
bind -f  ~/.inputrc

# Perforce defaults:
export P4EDITOR=vim

function mycp() { rsync -ah --progress $@; }
function g() { grep --recursive --color=always --line-number --extended-regexp "$@"; }

set -o vi
export VISUAL=vim
export EDITOR=vim
