# If not running interactively, don't do anything
[[ $- != *i* ]] && return

. $HOME/.bashrc_pc_specific

HISTSIZE=15000
HISTFILESIZE=20000

alias ls="ls --color"
alias grep="grep --line-number --color --extended-regexp"
# these turn on terminal coloring for ls and grep

# Have the prompt default to be the pwd
export PS1="\w$ "

#Case insenstive completion
bind -f  ~/.inputrc
